# Generated by Django 4.0.6 on 2022-12-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_companies',
            field=models.ManyToManyField(blank=True, related_name='staff_companies', to='users.company'),
        ),
    ]
