# Generated by Django 4.0.6 on 2022-12-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_staff_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='staff_companies',
            field=models.ManyToManyField(blank=True, help_text='Compañías a las que puede acceder el usuario.', related_name='staff_companies', to='users.company'),
        ),
    ]
