# Generated by Django 4.0.6 on 2022-10-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(auto_now_add=True)),
                ('attention_date', models.DateField(blank=True, null=True)),
                ('report_id', models.CharField(blank=True, max_length=64, null=True)),
                ('serial_number', models.CharField(db_index=True, max_length=64)),
                ('failure_id', models.CharField(max_length=64)),
                ('failure_description', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=1024)),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ('-report_date', '-pk'),
            },
        ),
    ]
