# Generated by Django 4.0.6 on 2022-10-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='serial_number_id',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
    ]
