# Generated by Django 4.0.6 on 2022-10-07 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_company'),
        ('tickets', '0003_ticket_serial_number_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=64)),
                ('serial_number_id', models.CharField(db_index=True, max_length=64, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.company')),
            ],
        ),
        migrations.CreateModel(
            name='FailureCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_id', models.CharField(db_index=True, max_length=64)),
                ('failure_description', models.CharField(max_length=64)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.company')),
            ],
        ),
    ]
