# Generated by Django 4.0.6 on 2022-10-07 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_serialnumber_failurecatalogue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='failurecatalogue',
            name='company',
        ),
    ]
