# Generated by Django 4.0.6 on 2022-10-07 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_failurecatalogue_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='failure_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tickets.failurecatalogue'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='serial_number_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tickets.serialnumber'),
        ),
    ]
