# Generated by Django 4.0.6 on 2022-10-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_failure_instance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialnumber',
            name='adrscode',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='serialnumber',
            name='offid',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='serialnumber',
            name='svcarea',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='serialnumber',
            name='techid',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='serialnumber',
            name='timezone',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
