# Generated by Django 4.0.6 on 2022-10-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_serialnumber_adrscode_serialnumber_offid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialnumber',
            name='itemnmbr',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
