# Generated by Django 4.0.6 on 2022-10-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_serialnumber_itemnmbr'),
    ]

    operations = [
        migrations.AddField(
            model_name='failurecatalogue',
            name='probcde',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
