# Generated by Django 4.0.6 on 2022-10-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_failurecatalogue_probcde'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='insert_200',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='insert_201',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='insert_202',
            field=models.BooleanField(default=False),
        ),
    ]
