# Generated by Django 4.0.6 on 2022-12-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_ticket_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='attention_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='report_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
