# Generated by Django 4.0.6 on 2022-12-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_alter_ticket_description_alter_ticket_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='comments',
            field=models.TextField(editable=False, null=True),
        ),
    ]
