# Generated by Django 4.0.6 on 2022-12-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_ticket_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
