# Generated by Django 4.0.6 on 2023-01-24 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_alter_ticket_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.ticket')),
            ],
        ),
    ]
