# Generated by Django 4.0.6 on 2023-02-16 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_ticketfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketfile',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket'),
        ),
    ]
