# Generated by Django 4.0.6 on 2023-03-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_alter_ticketfile_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='error_detail',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
