# Generated by Django 4.0.6 on 2023-05-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_ticket_error_detail_alter_ticket_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='area',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='counter',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='floor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
