# Generated by Django 4.0.6 on 2023-06-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_ticket_area_ticket_counter_ticket_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='insert_SY03900',
            field=models.BooleanField(default=False),
        ),
    ]
