# Generated by Django 4.0.6 on 2025-09-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_ticket_insert_sy03900'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='customer_reference',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='techid',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
